FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y procps curl
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
RUN mkdir -p /app/logs && chmod -R 777 /app/logs
CMD ["python", "-m", "app.playground_app"]
